name: Deploy Django App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest

    environment: potfolio  # the environment name on GitHub

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      working-directory: ./backend/portfolio_backend  # Navigate to where requirements.txt is located
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      working-directory: ./portfolio_backend  # Navigate to where manage.py is located
      run: python manage.py test

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.6

    - name: Terraform Init
      working-directory: ./portfolio_backend/terraform  # Navigate to where Terraform configuration is located
      run: terraform init

    - name: Terraform Plan
      working-directory: ./portfolio_backend/terraform  # Navigate to where Terraform configuration is located
      run: terraform plan

    - name: Terraform Apply
      working-directory: ./backend/portfolio_backend/terraform  # Navigate to where Terraform configuration is located
      run: terraform apply -auto-approve

    - name: Fetch EC2 Public IP
      id: output
      working-directory: ./backend/portfolio_backend/terraform  # Navigate to where Terraform configuration is located
      run: echo "EC2_IP=$(terraform output -raw ec2_public_ip)" >> $GITHUB_ENV

    - name: Post-deploy Verification
      run: |
        echo "Deployment Completed."
        echo "Application is available at http://${{ env.EC2_IP }}/"
