services:
  app:
    build:
      context: .
    command: >
      sh -c "wait-for-it db:5432 --timeout=30 -- python manage.py makemigrations && python manage.py migrate &&
             gunicorn portfolio_backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/app/portfolio_backend/static
      - media_volume:/app/portfolio_backend/media
    env_file:
      - .env
    expose:
      - 8000
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/portfolio_backend/static
      - media_volume:/app/portfolio_backend/media
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  static_volume:
  media_volume:
  postgres_data:
